// <auto-generated />
namespace QCon12.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Secon : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206092131152_Secon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1azXLbNhC+d6bvwOGp7UxE2Z3JJB4pGUe2Wk/jn1pqrh6YXMmYgAALgq70bD30kfoKBfgnkAApSrJlNclNArDfLhaLxeID//37n8H7RUicR+AxZnToHvX6rgPUZwGm86GbiNmrN+77d99/NzgPwoXzqRh3rMZJSRoP3QchohPPi/0HCFHcC7HPWcxmouez0EMB8477/TfeUd8DCeFKLMcZ3CZU4BDSP/LviFEfIpEgcskCIHHeLnsmKapzhUKII+TD0P1dDj467mUDXeeUYCSNmACZbWhR/62yyC11SW3n0iqxnC4jSDUO3RtEIBYcUQH6QDn0N1hWGmTTDWcRcLG8hVkufhG4jleV8+qCpZgmoyyQv6j4+dh1rhJC0D2RDTNEYnCd6PXJRDAOvwAFjgQEN0gI4FTJQjqD3BMn0etuznjr9Y+VMzxEKRNIyDU2DK+ZecVCKAydCC7DxXXGeAHBR6Bz8VAae4kWRYv86Tp/UCyjSwoJnoA+uex/u9IPmO1d5/QvrLy7d71jJvY/2fMQYfLMWgfeapu1br4pR/7nb9vu69x2H9n8uZV2DsTiFPgWiy8fi2lSWO+gdpBfGUd8FdRn0oNTHMLGOFp5sKtJZxD7HPtoDzvtCj3iebrCNt+6zi2QtDd+wFFWWfWKid7lQ8achbeMaC7Ieu4mLOG+igpm7Z4iPgfR3SK9/mq1qzLQYp3W32yjPshmaVPCOI1j5uPUtprdd7Yz7JwGTrvzsgDQJyjXPCECRwT70oCh+5Phw0bUYiYaar6KVcgjt57NrukZEBDgnPoiLftHKPZRYEaU9EtQbZEJELjKRIjIel1Zg6kwsyWmPo4QaTW8JtUxyyqrSvx6zxlEQFWibF2HLorLdGRqL5XUfLXONQNPi6eOYdZ8T7GEhXUvPFHI2baQBTvdpgcbfpZJ7DMILevTRX3tMNpDQGbZUMoIKQE8tyO7oKtWWAgjGpXEBIRps7zLr7Kr"
                       + "LVyM4KtCpTvRBpInuzXihao2MwwQzS8mUnFWaoPsp2l9odaeD6XtFbONBV97Img4hffqO6s6w01mX1m7Fh80pq7uyWt7f9jSlQUtC8/OvinqhHJnrPgsLyO0CuLLa2C+BpcoimT5pzFheYszyWiw0avJ5nxXmGF4fmyhvUprS03yhoHmUOuVqqWlY8xjIetmdI9UQToKQmNYpzxQ6LKkA3P5im1ZCKnfes7JScFeS0itHDmWcwtV9k0vUvZFN6VTShIRxC1XthEjSUibz4Jm6ewmpctnLd0R0iu6DpA2dJcvWS4do2zsjpOxVjpI1tIdIaegdIi8ycQYeLXFNM48I2iMyqEaiJ3CNE+W2weoNe93CM0GuS81KDMOSAfIWg4mEFanze7JaodM9f+JiPK6VEkzTXeoZpySwNFxysbuOLWaWUdbU043Y2pMjo6nNe85fo1ypD6k1F6WJbXyY5CXAutf54zaIBviOtJJjzhQdcFkGQsIe2pAb/InGREs57sacIkonknPT9lnUC+NsnTZ/pWvZDXjOCAH/NSHlQfWMrobUoo6P0sfEfcfEP8hRIsfd+D/d8KpPaXthKU/j+0EVHny2gDp0J+xvo6Q0p+JnmPxXu7p57DXr/YMkxq72yNMIGconuwRZhuDjCeYJwiorZ8GcvJor6S9SZBsSQxvRb82XYqejWj9Ugn+lHF7AdL9ZcOnnfR52SA6FGreZO460/Pr2Pmszpdp/F6lzyxNttKnVv6+mb634TeQ1k2zaGX22+w3VTw38V9xhkb9dCG1rQz24TP7WowZNOw+pr0BaW/ehuVO1b5olckixvMVhPq+lYJf2aPlmAs6Y0XGqFlUDKnVKZcgkKyW0CkXeIZ8Ibt9iOP0a5FPiCTppeYeggt6nYgoEXLKEN6Tpe4MlXLa9KcvE1WbB9dR+vXFU0xBmolVwXdNPySYBKXdY7NOa4JQuSyvjNVaClUhz5cl0hWjHYFy95UpeAphRCRYfE0n"
                       + "6BGabVvvw6rHBmcYzTkK4xxjJS//yvALwsW7/wBRS2y1ky0AAA=="; }
        }
    }
}
