// <auto-generated />
namespace QCon12.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class First : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206091456331_First"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1a23LbNhB970z/gcOntjMRZXcmk3ikZBzbaj2JL7XUvHpgEpIxAQEWAF3p2/rQT+ovdMGbQBKkqItltcmbCC4OdhcHy12s/vnr78H7eUidJywk4WzoHvX6roOZzwPCZkM3VtNXb9z3777/bnARhHPncy53rOVgJpND91Gp6MTzpP+IQyR7IfEFl3yqej4PPRRw77jff+Md9T0MEC5gOc7gLmaKhDh5gMczznwcqRjRKx5gKrNxeDNOUJ1rFGIZIR8P3d9A+Oi4lwq6ziklCJQYYzpdU6P+W62RW6wFq12AVmoxWUQ4WXHo3iKKpRKIKWwKguhHvCgNwNCt4BEWanGHp9n0y8B1vPI8rzqxmGbM0RrAL6Z+Pnad65hS9EBhYIqoxK4TvT4ZKy7wL5hhgRQObpFSWDA9FycWZJ44iV53c8Zbr3+sneEhxrhCCva4pnhFzWse4lzRsRJAF9cZkTkOPmE2U4+Fsldono/AT9f5nRFgF0xSIsamcelz+6IfCN/7mpM/ifbu3tcdcbV/Yy9CROgzrzrwlses9fBNBPK/fDt2X+ex+8Rnz71oZyLmX4FvXHx5Lv7KBRJLPp6D8RMSYouP2nHOsfQF8dEemH2Nnsgs8Wj105IEOOcO0+StfCRRmsn0csbdZyIjwcM7Tg0upm/uxzwWvt4Fbn09QWKGVXeNzHynVa+SoEU7432zjqaQTdOmA3oqJfdJoltF73vbN+OCBU6781ICmAbCnsdUkYgSHxQYuj/VfNiImltioGa7WIbs93pHVXsNyzoa3JyhWhS07sqOjLdtpgU7IczGjkj5ABWAQgQiX+aMtCTQo3iual7QM8ZY1RkO1cOSXzY1a0aXoZJdtYFk271ier5Umxo1EMMvdaQ8WhhC9nhS/WytPCGF7iW1vc44OSEMnNx71Y9j2cJ1rC/tXYsPGo9M90OzuT9sx8SCltKzs2/ySFmcjGUF7aUldF5qew219uAKRRF8"
                       + "AI3aOxtxxmnhffZqvH6FHaYYni8thXahbbES5DRohitvYWnQdESEVPC5Rw9If5LPgrAm1ikO5GtZwkF9+/JjmU/Sv82Yk11D9FootXTkCGwLITtLzMT2Ta/PTi5BEEXCkiSecRqHrCnRbJud5m7m/HSkO0JSFJgAyUD3+UVdbWIUg91x0jrZBElHuiNkRa8JkQ3VMQZeZTOrnPFqpKmc4SoRO9E0C5abE9Qa9ztQs2He/5WUadVpAqQjB0OE5ddm+2C1RaT67zCiqBdNkGKwO45RL5pIxvD+OVJOB+xEyXPCVWTI5bruuM5tGorHcs5X90onnqQYNrZorxRLr61VlsFtqNXa+oCvA5LUbZdSXxMUVwpdbK0mfJuToJQar6RCSXoXhLAkvRtugIm0S3JYkvyDoki73auJUisQqiJFrCoKhUpBMMiS89Udulq2noq4DnjgiQQ6Ux8vpMJhTwv0xn/QM0ogOi4FrhAjU7B3wr9g3W2EYmLzTl9xsyllQA+43Ue0B1be6q55zWne0bInJPxHJH4I0fzHLXoAW+FU2mlbYZktsq2ASm2vNZAOvZX1dVDKbBU9x+a9XPvnsPev0ooJQD21k1bMdgGmSKYMH64HUf3YdgTaebvCSN3XayRYrx43vOoHLmOhqYYoJA96DqkXMreCMJ9EiJY0r2dQXQ6IdmSBV31zjiPMNPOrxnVZq62mKIArh3WV+c/dsyky9k36KC/Og/Z70Zdlw+pSYuecsLev6rfbnVtYqzpYaeYNsflBB9c0cLW2GKw9ruYWlw2/obHTZEVr96tN//oSz90cKznDuB7t0vixdnkOv/tlcKzWqtiH2Ws0tur1KZxU43+mEC0kmS0hdOHNsF86o4XMJZvyPGRUNMpFKknDFVYIUiB0KhSZIl/Bax9Lmfyn5DOicVJmPODgkt3EKooVmIzDB7ownaFDTtv6SfeurPPgJkr+o7ELE0BNorO4G/YhJjQo9B7Vs7gmCB3LslxV"
                       + "76XSOetsUSBdc9YRKHNfEYInOIwogMkbNkZPuFm31T4se2xwTtBMoFBmGMv58Aj0C8L5u38BZo22jyktAAA="; }
        }
    }
}
